# Generated by Django 4.2.18 on 2025-01-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('combi', 'Combi'), ('suv', 'SUV')], default='sedan', max_length=10),
        ),
    ]
